export const translationType = {
    TRANSLATION_REQUEST: 'TRANSLATION_REQUEST',
    TRANSLATION_SUCCESS: 'TRANSLATION_SUCCESS',
    TRANSLATION_FAILURE: 'TRANSLATION_FAILURE',
};
export const authType = {
    AUTH_REQUEST: "AUTH_REQUEST",
    AUTH_SUCCESS: "AUTH_SUCCESS",
    AUTH_FAILURE: "AUTH_FAILURE",
    AUTH_REGISTER_REQUEST: 'AUTH_REGISTER_REQUEST',
    AUTH_INITIAL_REQUEST: 'AUTH_INITIAL_REQUEST',
    AUTH_LOGOUT_REQUEST: 'AUTH_LOGOUT_REQUEST',
};
export const bannerType = {
    BANNER_CREATE_REQUEST: "BANNER_CREATE_REQUEST",
    BANNER_CREATE_SUCCESS: "BANNER_CREATE_SUCCESS",
    BANNER_CREATE_FAILURE: "BANNER_CREATE_FAILURE",

    BANNER_LIST_REQUEST: "BANNER_LIST_REQUEST",
    BANNER_LIST_SUCCESS: "BANNER_LIST_SUCCESS",
    BANNER_LIST_FAILURE: "BANNER_LIST_FAILURE",

    BANNER_ACTIVE_REQUEST: "BANNER_ACTIVE_REQUEST",
    BANNER_ACTIVE_SUCCESS: "BANNER_ACTIVE_SUCCESS",
    BANNER_ACTIVE_FAILURE: "BANNER_ACTIVE_FAILURE",

    BANNER_UPDATE_REQUEST: "BANNER_UPDATE_REQUEST",
    BANNER_UPDATE_SUCCESS: "BANNER_UPDATE_SUCCESS",
    BANNER_UPDATE_FAILURE: "BANNER_UPDATE_FAILURE",

    BANNER_PARSE: "BANNER_PARSE",

    BANNER_DELETE_REQUEST: "BANNER_DELETE_REQUEST",
    BANNER_DELETE_SUCCESS: "BANNER_DELETE_SUCCESS",
    BANNER_DELETE_FAILURE: "BANNER_DELETE_FAILURE",
};
export const userType = {
    USER_ALL_REQUEST: "USER_ALL_REQUEST",
    USER_ALL_SUCCESS: "USER_ALL_SUCCESS",
    USER_ALL_FAILURE: "USER_ALL_FAILURE",
};
export const studioType = {
    STUDIO_CREATE_REQUEST: "STUDIO_CREATE_REQUEST",
    STUDIO_CREATE_SUCCESS: "STUDIO_CREATE_SUCCESS",
    STUDIO_CREATE_FAILURE: "STUDIO_CREATE_FAILURE",

    STUDIO_PARSE: "STUDIO_PARSE",

    STUDIO_UPDATE_PRICES_SUCCESS: "STUDIO_UPDATE_PRICES_SUCCESS",
    STUDIO_UPDATE_PRICES_FAILURE: "STUDIO_UPDATE_PRICES_FAILURE",

    STUDIO_UPDATE_IMAGES_FAILURE: "STUDIO_UPDATE_IMAGES_FAILURE",
    STUDIO_UPDATE_IMAGES_SUCCESS: "STUDIO_UPDATE_IMAGES_SUCCESS",

    STUDIO_ALL_FAILURE: "STUDIO_ALL_FAILURE",
    STUDIO_ALL_SUCCESS: "STUDIO_ALL_SUCCESS",

    STUDIO_GET_ALL_PRICES_FAILURE: "STUDIO_GET_ALL_PRICES_FAILURE",
    STUDIO_GET_ALL_PRICES_REQUEST: "STUDIO_GET_ALL_PRICES_REQUEST",
    STUDIO_GET_ALL_PRICES_SUCCESS: "STUDIO_GET_ALL_PRICES_SUCCESS",
};
export const storeType = {
    STORE_GET_ALL_STUDIO_REQUEST: "STORE_GET_ALL_STUDIO_REQUEST",
    STORE_GET_ALL_STUDIO_FAILURE: "STORE_GET_ALL_STUDIO_FAILURE",
    STORE_GET_ALL_STUDIO_SUCCESS: "STORE_GET_ALL_STUDIO_SUCCESS",
}