version: '3'
services:
  redis:
    expose:
      - 6379
    ports:
      - "6384:6379"
    container_name: SimplePOSRedis
    image: "redis:alpine"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    expose:
      - 5432
    ports:
      - 5430:5432