// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: proto/bannerService.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BannerServiceCreateRq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token    string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle string `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Route    string `protobuf:"bytes,4,opt,name=route,proto3" json:"route,omitempty"`
	Button   string `protobuf:"bytes,5,opt,name=button,proto3" json:"button,omitempty"`
	Page     string `protobuf:"bytes,6,opt,name=page,proto3" json:"page,omitempty"`
	Image    string `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *BannerServiceCreateRq) Reset() {
	*x = BannerServiceCreateRq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bannerService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BannerServiceCreateRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerServiceCreateRq) ProtoMessage() {}

func (x *BannerServiceCreateRq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bannerService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerServiceCreateRq.ProtoReflect.Descriptor instead.
func (*BannerServiceCreateRq) Descriptor() ([]byte, []int) {
	return file_proto_bannerService_proto_rawDescGZIP(), []int{0}
}

func (x *BannerServiceCreateRq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *BannerServiceCreateRq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BannerServiceCreateRq) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *BannerServiceCreateRq) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *BannerServiceCreateRq) GetButton() string {
	if x != nil {
		return x.Button
	}
	return ""
}

func (x *BannerServiceCreateRq) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *BannerServiceCreateRq) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type BannerServiceUpdateRq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token    string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle string `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Route    string `protobuf:"bytes,4,opt,name=route,proto3" json:"route,omitempty"`
	Button   string `protobuf:"bytes,5,opt,name=button,proto3" json:"button,omitempty"`
	Page     string `protobuf:"bytes,6,opt,name=page,proto3" json:"page,omitempty"`
	Image    string `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
	Id       int64  `protobuf:"varint,8,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BannerServiceUpdateRq) Reset() {
	*x = BannerServiceUpdateRq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bannerService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BannerServiceUpdateRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerServiceUpdateRq) ProtoMessage() {}

func (x *BannerServiceUpdateRq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bannerService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerServiceUpdateRq.ProtoReflect.Descriptor instead.
func (*BannerServiceUpdateRq) Descriptor() ([]byte, []int) {
	return file_proto_bannerService_proto_rawDescGZIP(), []int{1}
}

func (x *BannerServiceUpdateRq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *BannerServiceUpdateRq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BannerServiceUpdateRq) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *BannerServiceUpdateRq) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *BannerServiceUpdateRq) GetButton() string {
	if x != nil {
		return x.Button
	}
	return ""
}

func (x *BannerServiceUpdateRq) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *BannerServiceUpdateRq) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *BannerServiceUpdateRq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BannerServiceBool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *BannerServiceBool) Reset() {
	*x = BannerServiceBool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bannerService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BannerServiceBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerServiceBool) ProtoMessage() {}

func (x *BannerServiceBool) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bannerService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerServiceBool.ProtoReflect.Descriptor instead.
func (*BannerServiceBool) Descriptor() ([]byte, []int) {
	return file_proto_bannerService_proto_rawDescGZIP(), []int{2}
}

func (x *BannerServiceBool) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type BannerServiceGetAllRq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *BannerServiceGetAllRq) Reset() {
	*x = BannerServiceGetAllRq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bannerService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BannerServiceGetAllRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerServiceGetAllRq) ProtoMessage() {}

func (x *BannerServiceGetAllRq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bannerService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerServiceGetAllRq.ProtoReflect.Descriptor instead.
func (*BannerServiceGetAllRq) Descriptor() ([]byte, []int) {
	return file_proto_bannerService_proto_rawDescGZIP(), []int{3}
}

func (x *BannerServiceGetAllRq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Banner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle string `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Route    string `protobuf:"bytes,4,opt,name=route,proto3" json:"route,omitempty"`
	Button   string `protobuf:"bytes,5,opt,name=button,proto3" json:"button,omitempty"`
	Page     string `protobuf:"bytes,6,opt,name=page,proto3" json:"page,omitempty"`
	Image    string `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
	Active   bool   `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
}

func (x *Banner) Reset() {
	*x = Banner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bannerService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Banner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner) ProtoMessage() {}

func (x *Banner) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bannerService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner.ProtoReflect.Descriptor instead.
func (*Banner) Descriptor() ([]byte, []int) {
	return file_proto_bannerService_proto_rawDescGZIP(), []int{4}
}

func (x *Banner) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Banner) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Banner) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *Banner) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *Banner) GetButton() string {
	if x != nil {
		return x.Button
	}
	return ""
}

func (x *Banner) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *Banner) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Banner) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type BannerServiceGetAllRs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*Banner `protobuf:"bytes,1,rep,name=Result,proto3" json:"Result,omitempty"`
	Count  int64     `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *BannerServiceGetAllRs) Reset() {
	*x = BannerServiceGetAllRs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bannerService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BannerServiceGetAllRs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerServiceGetAllRs) ProtoMessage() {}

func (x *BannerServiceGetAllRs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bannerService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerServiceGetAllRs.ProtoReflect.Descriptor instead.
func (*BannerServiceGetAllRs) Descriptor() ([]byte, []int) {
	return file_proto_bannerService_proto_rawDescGZIP(), []int{5}
}

func (x *BannerServiceGetAllRs) GetResult() []*Banner {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *BannerServiceGetAllRs) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type BannerServiceActiveRq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Active bool   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	Id     int64  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BannerServiceActiveRq) Reset() {
	*x = BannerServiceActiveRq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bannerService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BannerServiceActiveRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerServiceActiveRq) ProtoMessage() {}

func (x *BannerServiceActiveRq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bannerService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerServiceActiveRq.ProtoReflect.Descriptor instead.
func (*BannerServiceActiveRq) Descriptor() ([]byte, []int) {
	return file_proto_bannerService_proto_rawDescGZIP(), []int{6}
}

func (x *BannerServiceActiveRq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *BannerServiceActiveRq) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *BannerServiceActiveRq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BannerServiceDeleteRq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id    int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BannerServiceDeleteRq) Reset() {
	*x = BannerServiceDeleteRq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bannerService_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BannerServiceDeleteRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerServiceDeleteRq) ProtoMessage() {}

func (x *BannerServiceDeleteRq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bannerService_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerServiceDeleteRq.ProtoReflect.Descriptor instead.
func (*BannerServiceDeleteRq) Descriptor() ([]byte, []int) {
	return file_proto_bannerService_proto_rawDescGZIP(), []int{7}
}

func (x *BannerServiceDeleteRq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *BannerServiceDeleteRq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_bannerService_proto protoreflect.FileDescriptor

var file_proto_bannerService_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xb7, 0x01, 0x0a, 0x15, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x71, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75,
	0x74, 0x74, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x74, 0x74,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0xc7, 0x01, 0x0a,
	0x15, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2d, 0x0a, 0x11, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x2d, 0x0a, 0x15, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x71, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xba, 0x01, 0x0a, 0x06, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x74, 0x74, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x22, 0x54, 0x0a, 0x15, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x55, 0x0a, 0x15, 0x42, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x52, 0x71,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3d,
	0x0a, 0x15, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x32, 0xe1, 0x02,
	0x0a, 0x0d, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x40, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x42, 0x6f, 0x6f,
	0x6c, 0x12, 0x44, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x71, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x71, 0x12, 0x44, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x71, 0x1a,
	0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x73, 0x12, 0x40, 0x0a,
	0x06, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x52, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x42, 0x6f, 0x6f, 0x6c, 0x12,
	0x40, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x42, 0x6f, 0x6f,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_bannerService_proto_rawDescOnce sync.Once
	file_proto_bannerService_proto_rawDescData = file_proto_bannerService_proto_rawDesc
)

func file_proto_bannerService_proto_rawDescGZIP() []byte {
	file_proto_bannerService_proto_rawDescOnce.Do(func() {
		file_proto_bannerService_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_bannerService_proto_rawDescData)
	})
	return file_proto_bannerService_proto_rawDescData
}

var file_proto_bannerService_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_bannerService_proto_goTypes = []interface{}{
	(*BannerServiceCreateRq)(nil), // 0: proto.BannerServiceCreateRq
	(*BannerServiceUpdateRq)(nil), // 1: proto.BannerServiceUpdateRq
	(*BannerServiceBool)(nil),     // 2: proto.BannerServiceBool
	(*BannerServiceGetAllRq)(nil), // 3: proto.BannerServiceGetAllRq
	(*Banner)(nil),                // 4: proto.Banner
	(*BannerServiceGetAllRs)(nil), // 5: proto.BannerServiceGetAllRs
	(*BannerServiceActiveRq)(nil), // 6: proto.BannerServiceActiveRq
	(*BannerServiceDeleteRq)(nil), // 7: proto.BannerServiceDeleteRq
}
var file_proto_bannerService_proto_depIdxs = []int32{
	4, // 0: proto.BannerServiceGetAllRs.Result:type_name -> proto.Banner
	0, // 1: proto.BannerService.Create:input_type -> proto.BannerServiceCreateRq
	1, // 2: proto.BannerService.Update:input_type -> proto.BannerServiceUpdateRq
	3, // 3: proto.BannerService.GetAll:input_type -> proto.BannerServiceGetAllRq
	6, // 4: proto.BannerService.Active:input_type -> proto.BannerServiceActiveRq
	7, // 5: proto.BannerService.Delete:input_type -> proto.BannerServiceDeleteRq
	2, // 6: proto.BannerService.Create:output_type -> proto.BannerServiceBool
	1, // 7: proto.BannerService.Update:output_type -> proto.BannerServiceUpdateRq
	5, // 8: proto.BannerService.GetAll:output_type -> proto.BannerServiceGetAllRs
	2, // 9: proto.BannerService.Active:output_type -> proto.BannerServiceBool
	2, // 10: proto.BannerService.Delete:output_type -> proto.BannerServiceBool
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_bannerService_proto_init() }
func file_proto_bannerService_proto_init() {
	if File_proto_bannerService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_bannerService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BannerServiceCreateRq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bannerService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BannerServiceUpdateRq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bannerService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BannerServiceBool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bannerService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BannerServiceGetAllRq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bannerService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Banner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bannerService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BannerServiceGetAllRs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bannerService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BannerServiceActiveRq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bannerService_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BannerServiceDeleteRq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_bannerService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bannerService_proto_goTypes,
		DependencyIndexes: file_proto_bannerService_proto_depIdxs,
		MessageInfos:      file_proto_bannerService_proto_msgTypes,
	}.Build()
	File_proto_bannerService_proto = out.File
	file_proto_bannerService_proto_rawDesc = nil
	file_proto_bannerService_proto_goTypes = nil
	file_proto_bannerService_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BannerServiceClient is the client API for BannerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BannerServiceClient interface {
	Create(ctx context.Context, in *BannerServiceCreateRq, opts ...grpc.CallOption) (*BannerServiceBool, error)
	Update(ctx context.Context, in *BannerServiceUpdateRq, opts ...grpc.CallOption) (*BannerServiceUpdateRq, error)
	GetAll(ctx context.Context, in *BannerServiceGetAllRq, opts ...grpc.CallOption) (*BannerServiceGetAllRs, error)
	Active(ctx context.Context, in *BannerServiceActiveRq, opts ...grpc.CallOption) (*BannerServiceBool, error)
	Delete(ctx context.Context, in *BannerServiceDeleteRq, opts ...grpc.CallOption) (*BannerServiceBool, error)
}

type bannerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBannerServiceClient(cc grpc.ClientConnInterface) BannerServiceClient {
	return &bannerServiceClient{cc}
}

func (c *bannerServiceClient) Create(ctx context.Context, in *BannerServiceCreateRq, opts ...grpc.CallOption) (*BannerServiceBool, error) {
	out := new(BannerServiceBool)
	err := c.cc.Invoke(ctx, "/proto.BannerService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerServiceClient) Update(ctx context.Context, in *BannerServiceUpdateRq, opts ...grpc.CallOption) (*BannerServiceUpdateRq, error) {
	out := new(BannerServiceUpdateRq)
	err := c.cc.Invoke(ctx, "/proto.BannerService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerServiceClient) GetAll(ctx context.Context, in *BannerServiceGetAllRq, opts ...grpc.CallOption) (*BannerServiceGetAllRs, error) {
	out := new(BannerServiceGetAllRs)
	err := c.cc.Invoke(ctx, "/proto.BannerService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerServiceClient) Active(ctx context.Context, in *BannerServiceActiveRq, opts ...grpc.CallOption) (*BannerServiceBool, error) {
	out := new(BannerServiceBool)
	err := c.cc.Invoke(ctx, "/proto.BannerService/Active", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerServiceClient) Delete(ctx context.Context, in *BannerServiceDeleteRq, opts ...grpc.CallOption) (*BannerServiceBool, error) {
	out := new(BannerServiceBool)
	err := c.cc.Invoke(ctx, "/proto.BannerService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BannerServiceServer is the server API for BannerService service.
type BannerServiceServer interface {
	Create(context.Context, *BannerServiceCreateRq) (*BannerServiceBool, error)
	Update(context.Context, *BannerServiceUpdateRq) (*BannerServiceUpdateRq, error)
	GetAll(context.Context, *BannerServiceGetAllRq) (*BannerServiceGetAllRs, error)
	Active(context.Context, *BannerServiceActiveRq) (*BannerServiceBool, error)
	Delete(context.Context, *BannerServiceDeleteRq) (*BannerServiceBool, error)
}

// UnimplementedBannerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBannerServiceServer struct {
}

func (*UnimplementedBannerServiceServer) Create(context.Context, *BannerServiceCreateRq) (*BannerServiceBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedBannerServiceServer) Update(context.Context, *BannerServiceUpdateRq) (*BannerServiceUpdateRq, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedBannerServiceServer) GetAll(context.Context, *BannerServiceGetAllRq) (*BannerServiceGetAllRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (*UnimplementedBannerServiceServer) Active(context.Context, *BannerServiceActiveRq) (*BannerServiceBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Active not implemented")
}
func (*UnimplementedBannerServiceServer) Delete(context.Context, *BannerServiceDeleteRq) (*BannerServiceBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterBannerServiceServer(s *grpc.Server, srv BannerServiceServer) {
	s.RegisterService(&_BannerService_serviceDesc, srv)
}

func _BannerService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BannerServiceCreateRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BannerService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServiceServer).Create(ctx, req.(*BannerServiceCreateRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BannerService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BannerServiceUpdateRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BannerService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServiceServer).Update(ctx, req.(*BannerServiceUpdateRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BannerService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BannerServiceGetAllRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BannerService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServiceServer).GetAll(ctx, req.(*BannerServiceGetAllRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BannerService_Active_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BannerServiceActiveRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServiceServer).Active(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BannerService/Active",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServiceServer).Active(ctx, req.(*BannerServiceActiveRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BannerService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BannerServiceDeleteRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BannerService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServiceServer).Delete(ctx, req.(*BannerServiceDeleteRq))
	}
	return interceptor(ctx, in, info, handler)
}

var _BannerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BannerService",
	HandlerType: (*BannerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _BannerService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _BannerService_Update_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _BannerService_GetAll_Handler,
		},
		{
			MethodName: "Active",
			Handler:    _BannerService_Active_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BannerService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/bannerService.proto",
}
