// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: proto/studioService.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type StudioServiceCreateRq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token       string  `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Title       string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Size        string  `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	Capacity    int32   `protobuf:"varint,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	PriceFrom   float32 `protobuf:"fixed32,6,opt,name=priceFrom,proto3" json:"priceFrom,omitempty"`
	Active      bool    `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
}

func (x *StudioServiceCreateRq) Reset() {
	*x = StudioServiceCreateRq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_studioService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudioServiceCreateRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudioServiceCreateRq) ProtoMessage() {}

func (x *StudioServiceCreateRq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_studioService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudioServiceCreateRq.ProtoReflect.Descriptor instead.
func (*StudioServiceCreateRq) Descriptor() ([]byte, []int) {
	return file_proto_studioService_proto_rawDescGZIP(), []int{0}
}

func (x *StudioServiceCreateRq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *StudioServiceCreateRq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *StudioServiceCreateRq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StudioServiceCreateRq) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *StudioServiceCreateRq) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *StudioServiceCreateRq) GetPriceFrom() float32 {
	if x != nil {
		return x.PriceFrom
	}
	return 0
}

func (x *StudioServiceCreateRq) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type StudioServiceUpdateRq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token       string  `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Title       string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Size        string  `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	Capacity    int32   `protobuf:"varint,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	PriceFrom   float32 `protobuf:"fixed32,6,opt,name=priceFrom,proto3" json:"priceFrom,omitempty"`
	Active      bool    `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
	Id          int64   `protobuf:"varint,8,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StudioServiceUpdateRq) Reset() {
	*x = StudioServiceUpdateRq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_studioService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudioServiceUpdateRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudioServiceUpdateRq) ProtoMessage() {}

func (x *StudioServiceUpdateRq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_studioService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudioServiceUpdateRq.ProtoReflect.Descriptor instead.
func (*StudioServiceUpdateRq) Descriptor() ([]byte, []int) {
	return file_proto_studioService_proto_rawDescGZIP(), []int{1}
}

func (x *StudioServiceUpdateRq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *StudioServiceUpdateRq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *StudioServiceUpdateRq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StudioServiceUpdateRq) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *StudioServiceUpdateRq) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *StudioServiceUpdateRq) GetPriceFrom() float32 {
	if x != nil {
		return x.PriceFrom
	}
	return 0
}

func (x *StudioServiceUpdateRq) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *StudioServiceUpdateRq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StudioServiceBool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *StudioServiceBool) Reset() {
	*x = StudioServiceBool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_studioService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudioServiceBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudioServiceBool) ProtoMessage() {}

func (x *StudioServiceBool) ProtoReflect() protoreflect.Message {
	mi := &file_proto_studioService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudioServiceBool.ProtoReflect.Descriptor instead.
func (*StudioServiceBool) Descriptor() ([]byte, []int) {
	return file_proto_studioService_proto_rawDescGZIP(), []int{2}
}

func (x *StudioServiceBool) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StudioServiceGetAllRq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *StudioServiceGetAllRq) Reset() {
	*x = StudioServiceGetAllRq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_studioService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudioServiceGetAllRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudioServiceGetAllRq) ProtoMessage() {}

func (x *StudioServiceGetAllRq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_studioService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudioServiceGetAllRq.ProtoReflect.Descriptor instead.
func (*StudioServiceGetAllRq) Descriptor() ([]byte, []int) {
	return file_proto_studioService_proto_rawDescGZIP(), []int{3}
}

func (x *StudioServiceGetAllRq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Studio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Size        string  `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	Capacity    int32   `protobuf:"varint,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	PriceFrom   float32 `protobuf:"fixed32,6,opt,name=priceFrom,proto3" json:"priceFrom,omitempty"`
	Active      bool    `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
	Image       string  `protobuf:"bytes,8,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *Studio) Reset() {
	*x = Studio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_studioService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Studio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Studio) ProtoMessage() {}

func (x *Studio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_studioService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Studio.ProtoReflect.Descriptor instead.
func (*Studio) Descriptor() ([]byte, []int) {
	return file_proto_studioService_proto_rawDescGZIP(), []int{4}
}

func (x *Studio) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Studio) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Studio) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Studio) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *Studio) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Studio) GetPriceFrom() float32 {
	if x != nil {
		return x.PriceFrom
	}
	return 0
}

func (x *Studio) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Studio) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type StudioServiceGetAllRs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*Studio `protobuf:"bytes,1,rep,name=Result,proto3" json:"Result,omitempty"`
	Count  int64     `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *StudioServiceGetAllRs) Reset() {
	*x = StudioServiceGetAllRs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_studioService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudioServiceGetAllRs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudioServiceGetAllRs) ProtoMessage() {}

func (x *StudioServiceGetAllRs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_studioService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudioServiceGetAllRs.ProtoReflect.Descriptor instead.
func (*StudioServiceGetAllRs) Descriptor() ([]byte, []int) {
	return file_proto_studioService_proto_rawDescGZIP(), []int{5}
}

func (x *StudioServiceGetAllRs) GetResult() []*Studio {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *StudioServiceGetAllRs) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type StudioServiceActiveRq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Active bool   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	Id     int64  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StudioServiceActiveRq) Reset() {
	*x = StudioServiceActiveRq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_studioService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudioServiceActiveRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudioServiceActiveRq) ProtoMessage() {}

func (x *StudioServiceActiveRq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_studioService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudioServiceActiveRq.ProtoReflect.Descriptor instead.
func (*StudioServiceActiveRq) Descriptor() ([]byte, []int) {
	return file_proto_studioService_proto_rawDescGZIP(), []int{6}
}

func (x *StudioServiceActiveRq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *StudioServiceActiveRq) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *StudioServiceActiveRq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StudioServiceDeleteRq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id    int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StudioServiceDeleteRq) Reset() {
	*x = StudioServiceDeleteRq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_studioService_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudioServiceDeleteRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudioServiceDeleteRq) ProtoMessage() {}

func (x *StudioServiceDeleteRq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_studioService_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudioServiceDeleteRq.ProtoReflect.Descriptor instead.
func (*StudioServiceDeleteRq) Descriptor() ([]byte, []int) {
	return file_proto_studioService_proto_rawDescGZIP(), []int{7}
}

func (x *StudioServiceDeleteRq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *StudioServiceDeleteRq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StudioServiceCreateRs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StudioServiceCreateRs) Reset() {
	*x = StudioServiceCreateRs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_studioService_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudioServiceCreateRs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudioServiceCreateRs) ProtoMessage() {}

func (x *StudioServiceCreateRs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_studioService_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudioServiceCreateRs.ProtoReflect.Descriptor instead.
func (*StudioServiceCreateRs) Descriptor() ([]byte, []int) {
	return file_proto_studioService_proto_rawDescGZIP(), []int{8}
}

func (x *StudioServiceCreateRs) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StudioServiceUpdatePricesRq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string    `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id     int64     `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Prices []*Prices `protobuf:"bytes,3,rep,name=prices,proto3" json:"prices,omitempty"`
}

func (x *StudioServiceUpdatePricesRq) Reset() {
	*x = StudioServiceUpdatePricesRq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_studioService_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudioServiceUpdatePricesRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudioServiceUpdatePricesRq) ProtoMessage() {}

func (x *StudioServiceUpdatePricesRq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_studioService_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudioServiceUpdatePricesRq.ProtoReflect.Descriptor instead.
func (*StudioServiceUpdatePricesRq) Descriptor() ([]byte, []int) {
	return file_proto_studioService_proto_rawDescGZIP(), []int{9}
}

func (x *StudioServiceUpdatePricesRq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *StudioServiceUpdatePricesRq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StudioServiceUpdatePricesRq) GetPrices() []*Prices {
	if x != nil {
		return x.Prices
	}
	return nil
}

type Prices struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsHour      bool    `protobuf:"varint,4,opt,name=isHour,proto3" json:"isHour,omitempty"`
	Price       float32 `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	FkStudio    int64   `protobuf:"varint,6,opt,name=fkStudio,proto3" json:"fkStudio,omitempty"`
}

func (x *Prices) Reset() {
	*x = Prices{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_studioService_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prices) ProtoMessage() {}

func (x *Prices) ProtoReflect() protoreflect.Message {
	mi := &file_proto_studioService_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prices.ProtoReflect.Descriptor instead.
func (*Prices) Descriptor() ([]byte, []int) {
	return file_proto_studioService_proto_rawDescGZIP(), []int{10}
}

func (x *Prices) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Prices) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Prices) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Prices) GetIsHour() bool {
	if x != nil {
		return x.IsHour
	}
	return false
}

func (x *Prices) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Prices) GetFkStudio() int64 {
	if x != nil {
		return x.FkStudio
	}
	return 0
}

type StudioServiceUpdateImagesRq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id    int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Image string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *StudioServiceUpdateImagesRq) Reset() {
	*x = StudioServiceUpdateImagesRq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_studioService_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudioServiceUpdateImagesRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudioServiceUpdateImagesRq) ProtoMessage() {}

func (x *StudioServiceUpdateImagesRq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_studioService_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudioServiceUpdateImagesRq.ProtoReflect.Descriptor instead.
func (*StudioServiceUpdateImagesRq) Descriptor() ([]byte, []int) {
	return file_proto_studioService_proto_rawDescGZIP(), []int{11}
}

func (x *StudioServiceUpdateImagesRq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *StudioServiceUpdateImagesRq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StudioServiceUpdateImagesRq) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type StudioServiceGetAllPricesRq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *StudioServiceGetAllPricesRq) Reset() {
	*x = StudioServiceGetAllPricesRq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_studioService_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudioServiceGetAllPricesRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudioServiceGetAllPricesRq) ProtoMessage() {}

func (x *StudioServiceGetAllPricesRq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_studioService_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudioServiceGetAllPricesRq.ProtoReflect.Descriptor instead.
func (*StudioServiceGetAllPricesRq) Descriptor() ([]byte, []int) {
	return file_proto_studioService_proto_rawDescGZIP(), []int{12}
}

func (x *StudioServiceGetAllPricesRq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type StudioServiceGetAllPricesRs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*Prices `protobuf:"bytes,1,rep,name=Result,proto3" json:"Result,omitempty"`
	Count  int64     `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *StudioServiceGetAllPricesRs) Reset() {
	*x = StudioServiceGetAllPricesRs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_studioService_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudioServiceGetAllPricesRs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudioServiceGetAllPricesRs) ProtoMessage() {}

func (x *StudioServiceGetAllPricesRs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_studioService_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudioServiceGetAllPricesRs.ProtoReflect.Descriptor instead.
func (*StudioServiceGetAllPricesRs) Descriptor() ([]byte, []int) {
	return file_proto_studioService_proto_rawDescGZIP(), []int{13}
}

func (x *StudioServiceGetAllPricesRs) GetResult() []*Prices {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *StudioServiceGetAllPricesRs) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_proto_studioService_proto protoreflect.FileDescriptor

var file_proto_studioService_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xcb, 0x01, 0x0a, 0x15, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x71, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x22, 0xdb, 0x01, 0x0a, 0x15, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2d,
	0x0a, 0x11, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x42,
	0x6f, 0x6f, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x2d, 0x0a,
	0x15, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x52, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xcc, 0x01, 0x0a,
	0x06, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12,
	0x1c, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x63, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x09, 0x70, 0x72, 0x69, 0x63, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x54, 0x0a, 0x15, 0x53,
	0x74, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x52, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x75,
	0x64, 0x69, 0x6f, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x55, 0x0a, 0x15, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x52, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3d, 0x0a, 0x15, 0x53, 0x74, 0x75, 0x64,
	0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x27, 0x0a, 0x15, 0x53, 0x74, 0x75, 0x64, 0x69,
	0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x6a, 0x0a, 0x1b, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x52, 0x71, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x06, 0x70, 0x72, 0x69, 0x63, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x73, 0x52, 0x06, 0x70, 0x72, 0x69, 0x63, 0x65, 0x73, 0x22, 0x9a, 0x01, 0x0a,
	0x06, 0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x69, 0x73, 0x48, 0x6f, 0x75, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x69, 0x73, 0x48, 0x6f, 0x75, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x66, 0x6b, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x66, 0x6b, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x22, 0x59, 0x0a, 0x1b, 0x53, 0x74, 0x75,
	0x64, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x52, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x22, 0x33, 0x0a, 0x1b, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x73, 0x52, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x5a, 0x0a, 0x1b, 0x53, 0x74, 0x75,
	0x64, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x52, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0xd9, 0x04, 0x0a, 0x0d, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x71, 0x1a,
	0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x73, 0x12, 0x44, 0x0a,
	0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x71, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74,
	0x75, 0x64, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x71, 0x12, 0x4c, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x73, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x75, 0x64,
	0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x73, 0x52, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x42, 0x6f, 0x6f,
	0x6c, 0x12, 0x4c, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x73, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x73, 0x52, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74,
	0x75, 0x64, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x42, 0x6f, 0x6f, 0x6c, 0x12,
	0x44, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x71, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x52, 0x73, 0x12, 0x56, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x73, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74,
	0x75, 0x64, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x52, 0x71, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x52, 0x73, 0x12, 0x40, 0x0a,
	0x06, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x52, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74,
	0x75, 0x64, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x42, 0x6f, 0x6f, 0x6c, 0x12,
	0x40, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x42, 0x6f, 0x6f,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_studioService_proto_rawDescOnce sync.Once
	file_proto_studioService_proto_rawDescData = file_proto_studioService_proto_rawDesc
)

func file_proto_studioService_proto_rawDescGZIP() []byte {
	file_proto_studioService_proto_rawDescOnce.Do(func() {
		file_proto_studioService_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_studioService_proto_rawDescData)
	})
	return file_proto_studioService_proto_rawDescData
}

var file_proto_studioService_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_studioService_proto_goTypes = []interface{}{
	(*StudioServiceCreateRq)(nil),       // 0: proto.StudioServiceCreateRq
	(*StudioServiceUpdateRq)(nil),       // 1: proto.StudioServiceUpdateRq
	(*StudioServiceBool)(nil),           // 2: proto.StudioServiceBool
	(*StudioServiceGetAllRq)(nil),       // 3: proto.StudioServiceGetAllRq
	(*Studio)(nil),                      // 4: proto.Studio
	(*StudioServiceGetAllRs)(nil),       // 5: proto.StudioServiceGetAllRs
	(*StudioServiceActiveRq)(nil),       // 6: proto.StudioServiceActiveRq
	(*StudioServiceDeleteRq)(nil),       // 7: proto.StudioServiceDeleteRq
	(*StudioServiceCreateRs)(nil),       // 8: proto.StudioServiceCreateRs
	(*StudioServiceUpdatePricesRq)(nil), // 9: proto.StudioServiceUpdatePricesRq
	(*Prices)(nil),                      // 10: proto.Prices
	(*StudioServiceUpdateImagesRq)(nil), // 11: proto.StudioServiceUpdateImagesRq
	(*StudioServiceGetAllPricesRq)(nil), // 12: proto.StudioServiceGetAllPricesRq
	(*StudioServiceGetAllPricesRs)(nil), // 13: proto.StudioServiceGetAllPricesRs
}
var file_proto_studioService_proto_depIdxs = []int32{
	4,  // 0: proto.StudioServiceGetAllRs.Result:type_name -> proto.Studio
	10, // 1: proto.StudioServiceUpdatePricesRq.prices:type_name -> proto.Prices
	10, // 2: proto.StudioServiceGetAllPricesRs.Result:type_name -> proto.Prices
	0,  // 3: proto.StudioService.Create:input_type -> proto.StudioServiceCreateRq
	1,  // 4: proto.StudioService.Update:input_type -> proto.StudioServiceUpdateRq
	9,  // 5: proto.StudioService.UpdatePrices:input_type -> proto.StudioServiceUpdatePricesRq
	11, // 6: proto.StudioService.UpdateImages:input_type -> proto.StudioServiceUpdateImagesRq
	3,  // 7: proto.StudioService.GetAll:input_type -> proto.StudioServiceGetAllRq
	12, // 8: proto.StudioService.GetAllPrices:input_type -> proto.StudioServiceGetAllPricesRq
	6,  // 9: proto.StudioService.Active:input_type -> proto.StudioServiceActiveRq
	7,  // 10: proto.StudioService.Delete:input_type -> proto.StudioServiceDeleteRq
	8,  // 11: proto.StudioService.Create:output_type -> proto.StudioServiceCreateRs
	1,  // 12: proto.StudioService.Update:output_type -> proto.StudioServiceUpdateRq
	2,  // 13: proto.StudioService.UpdatePrices:output_type -> proto.StudioServiceBool
	2,  // 14: proto.StudioService.UpdateImages:output_type -> proto.StudioServiceBool
	5,  // 15: proto.StudioService.GetAll:output_type -> proto.StudioServiceGetAllRs
	13, // 16: proto.StudioService.GetAllPrices:output_type -> proto.StudioServiceGetAllPricesRs
	2,  // 17: proto.StudioService.Active:output_type -> proto.StudioServiceBool
	2,  // 18: proto.StudioService.Delete:output_type -> proto.StudioServiceBool
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_studioService_proto_init() }
func file_proto_studioService_proto_init() {
	if File_proto_studioService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_studioService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudioServiceCreateRq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_studioService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudioServiceUpdateRq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_studioService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudioServiceBool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_studioService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudioServiceGetAllRq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_studioService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Studio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_studioService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudioServiceGetAllRs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_studioService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudioServiceActiveRq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_studioService_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudioServiceDeleteRq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_studioService_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudioServiceCreateRs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_studioService_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudioServiceUpdatePricesRq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_studioService_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Prices); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_studioService_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudioServiceUpdateImagesRq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_studioService_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudioServiceGetAllPricesRq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_studioService_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudioServiceGetAllPricesRs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_studioService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_studioService_proto_goTypes,
		DependencyIndexes: file_proto_studioService_proto_depIdxs,
		MessageInfos:      file_proto_studioService_proto_msgTypes,
	}.Build()
	File_proto_studioService_proto = out.File
	file_proto_studioService_proto_rawDesc = nil
	file_proto_studioService_proto_goTypes = nil
	file_proto_studioService_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StudioServiceClient is the client API for StudioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StudioServiceClient interface {
	Create(ctx context.Context, in *StudioServiceCreateRq, opts ...grpc.CallOption) (*StudioServiceCreateRs, error)
	Update(ctx context.Context, in *StudioServiceUpdateRq, opts ...grpc.CallOption) (*StudioServiceUpdateRq, error)
	UpdatePrices(ctx context.Context, in *StudioServiceUpdatePricesRq, opts ...grpc.CallOption) (*StudioServiceBool, error)
	UpdateImages(ctx context.Context, in *StudioServiceUpdateImagesRq, opts ...grpc.CallOption) (*StudioServiceBool, error)
	GetAll(ctx context.Context, in *StudioServiceGetAllRq, opts ...grpc.CallOption) (*StudioServiceGetAllRs, error)
	GetAllPrices(ctx context.Context, in *StudioServiceGetAllPricesRq, opts ...grpc.CallOption) (*StudioServiceGetAllPricesRs, error)
	Active(ctx context.Context, in *StudioServiceActiveRq, opts ...grpc.CallOption) (*StudioServiceBool, error)
	Delete(ctx context.Context, in *StudioServiceDeleteRq, opts ...grpc.CallOption) (*StudioServiceBool, error)
}

type studioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStudioServiceClient(cc grpc.ClientConnInterface) StudioServiceClient {
	return &studioServiceClient{cc}
}

func (c *studioServiceClient) Create(ctx context.Context, in *StudioServiceCreateRq, opts ...grpc.CallOption) (*StudioServiceCreateRs, error) {
	out := new(StudioServiceCreateRs)
	err := c.cc.Invoke(ctx, "/proto.StudioService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studioServiceClient) Update(ctx context.Context, in *StudioServiceUpdateRq, opts ...grpc.CallOption) (*StudioServiceUpdateRq, error) {
	out := new(StudioServiceUpdateRq)
	err := c.cc.Invoke(ctx, "/proto.StudioService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studioServiceClient) UpdatePrices(ctx context.Context, in *StudioServiceUpdatePricesRq, opts ...grpc.CallOption) (*StudioServiceBool, error) {
	out := new(StudioServiceBool)
	err := c.cc.Invoke(ctx, "/proto.StudioService/UpdatePrices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studioServiceClient) UpdateImages(ctx context.Context, in *StudioServiceUpdateImagesRq, opts ...grpc.CallOption) (*StudioServiceBool, error) {
	out := new(StudioServiceBool)
	err := c.cc.Invoke(ctx, "/proto.StudioService/UpdateImages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studioServiceClient) GetAll(ctx context.Context, in *StudioServiceGetAllRq, opts ...grpc.CallOption) (*StudioServiceGetAllRs, error) {
	out := new(StudioServiceGetAllRs)
	err := c.cc.Invoke(ctx, "/proto.StudioService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studioServiceClient) GetAllPrices(ctx context.Context, in *StudioServiceGetAllPricesRq, opts ...grpc.CallOption) (*StudioServiceGetAllPricesRs, error) {
	out := new(StudioServiceGetAllPricesRs)
	err := c.cc.Invoke(ctx, "/proto.StudioService/GetAllPrices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studioServiceClient) Active(ctx context.Context, in *StudioServiceActiveRq, opts ...grpc.CallOption) (*StudioServiceBool, error) {
	out := new(StudioServiceBool)
	err := c.cc.Invoke(ctx, "/proto.StudioService/Active", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studioServiceClient) Delete(ctx context.Context, in *StudioServiceDeleteRq, opts ...grpc.CallOption) (*StudioServiceBool, error) {
	out := new(StudioServiceBool)
	err := c.cc.Invoke(ctx, "/proto.StudioService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudioServiceServer is the server API for StudioService service.
type StudioServiceServer interface {
	Create(context.Context, *StudioServiceCreateRq) (*StudioServiceCreateRs, error)
	Update(context.Context, *StudioServiceUpdateRq) (*StudioServiceUpdateRq, error)
	UpdatePrices(context.Context, *StudioServiceUpdatePricesRq) (*StudioServiceBool, error)
	UpdateImages(context.Context, *StudioServiceUpdateImagesRq) (*StudioServiceBool, error)
	GetAll(context.Context, *StudioServiceGetAllRq) (*StudioServiceGetAllRs, error)
	GetAllPrices(context.Context, *StudioServiceGetAllPricesRq) (*StudioServiceGetAllPricesRs, error)
	Active(context.Context, *StudioServiceActiveRq) (*StudioServiceBool, error)
	Delete(context.Context, *StudioServiceDeleteRq) (*StudioServiceBool, error)
}

// UnimplementedStudioServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStudioServiceServer struct {
}

func (*UnimplementedStudioServiceServer) Create(context.Context, *StudioServiceCreateRq) (*StudioServiceCreateRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedStudioServiceServer) Update(context.Context, *StudioServiceUpdateRq) (*StudioServiceUpdateRq, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedStudioServiceServer) UpdatePrices(context.Context, *StudioServiceUpdatePricesRq) (*StudioServiceBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePrices not implemented")
}
func (*UnimplementedStudioServiceServer) UpdateImages(context.Context, *StudioServiceUpdateImagesRq) (*StudioServiceBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateImages not implemented")
}
func (*UnimplementedStudioServiceServer) GetAll(context.Context, *StudioServiceGetAllRq) (*StudioServiceGetAllRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (*UnimplementedStudioServiceServer) GetAllPrices(context.Context, *StudioServiceGetAllPricesRq) (*StudioServiceGetAllPricesRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllPrices not implemented")
}
func (*UnimplementedStudioServiceServer) Active(context.Context, *StudioServiceActiveRq) (*StudioServiceBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Active not implemented")
}
func (*UnimplementedStudioServiceServer) Delete(context.Context, *StudioServiceDeleteRq) (*StudioServiceBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterStudioServiceServer(s *grpc.Server, srv StudioServiceServer) {
	s.RegisterService(&_StudioService_serviceDesc, srv)
}

func _StudioService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudioServiceCreateRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudioServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StudioService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudioServiceServer).Create(ctx, req.(*StudioServiceCreateRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudioService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudioServiceUpdateRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudioServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StudioService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudioServiceServer).Update(ctx, req.(*StudioServiceUpdateRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudioService_UpdatePrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudioServiceUpdatePricesRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudioServiceServer).UpdatePrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StudioService/UpdatePrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudioServiceServer).UpdatePrices(ctx, req.(*StudioServiceUpdatePricesRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudioService_UpdateImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudioServiceUpdateImagesRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudioServiceServer).UpdateImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StudioService/UpdateImages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudioServiceServer).UpdateImages(ctx, req.(*StudioServiceUpdateImagesRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudioService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudioServiceGetAllRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudioServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StudioService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudioServiceServer).GetAll(ctx, req.(*StudioServiceGetAllRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudioService_GetAllPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudioServiceGetAllPricesRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudioServiceServer).GetAllPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StudioService/GetAllPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudioServiceServer).GetAllPrices(ctx, req.(*StudioServiceGetAllPricesRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudioService_Active_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudioServiceActiveRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudioServiceServer).Active(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StudioService/Active",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudioServiceServer).Active(ctx, req.(*StudioServiceActiveRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudioService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudioServiceDeleteRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudioServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StudioService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudioServiceServer).Delete(ctx, req.(*StudioServiceDeleteRq))
	}
	return interceptor(ctx, in, info, handler)
}

var _StudioService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StudioService",
	HandlerType: (*StudioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _StudioService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _StudioService_Update_Handler,
		},
		{
			MethodName: "UpdatePrices",
			Handler:    _StudioService_UpdatePrices_Handler,
		},
		{
			MethodName: "UpdateImages",
			Handler:    _StudioService_UpdateImages_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _StudioService_GetAll_Handler,
		},
		{
			MethodName: "GetAllPrices",
			Handler:    _StudioService_GetAllPrices_Handler,
		},
		{
			MethodName: "Active",
			Handler:    _StudioService_Active_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _StudioService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/studioService.proto",
}
